### ISSUE TITLE
[seven] segfault in apc_clear_cache()

### ISSUE THREAD

**Issue by bmadzar** [krakjoe/apcu#130]
Not sure if you're accepting bug reports for the PHP7 branch yet, but in case you are...

Calling `apc_clear_cache("user")` reliably results in a segfault. Tested on two different machines, both Debian Jessie x86_64.

Backtrace follows:

````
#0  __strncasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:235
#1  0x00007fea907b93b3 in zif_apcu_clear_cache () from /php7/lib/php/extensions/no-debug-non-zts-20141001/apcu.so
#2  0x00000000007eee52 in ZEND_DO_ICALL_SPEC_HANDLER ()
#3  0x00000000007b7178 in execute_ex ()
#4  0x00000000007b75de in zend_execute ()
#5  0x0000000000775f96 in zend_execute_scripts ()
#6  0x000000000070dccf in php_execute_script ()
#7  0x0000000000815692 in main ()
````

**Comment by krakjoe** [comment]
Thanks for the report :)
