### ISSUE TITLE
segfault when apc.preload_path contains bad data (PHP 5)

### ISSUE THREAD

**Issue by remicollet** [krakjoe/apcu#176]
```
#0  0x0000555555792cec in _zval_dtor_func (zvalue=0x7ffff7f7f0a8) at /usr/src/debug/php-5.6.20/Zend/zend_variables.c:57
#1  0x0000555555782f50 in _zval_dtor (zvalue=0x7ffff7f7f0a8) at /usr/src/debug/php-5.6.20/Zend/zend_variables.h:35
#2  i_zval_ptr_dtor (zval_ptr=0x7ffff7f7f0a8) at /usr/src/debug/php-5.6.20/Zend/zend_execute.h:79
#3  _zval_ptr_dtor (zval_ptr=zval_ptr@entry=0x7fffffffa698) at /usr/src/debug/php-5.6.20/Zend/zend_execute_API.c:424
#4  0x00007fffece8706e in data_unserialize (filename=0x7fffffffa740 "/work/GIT/apcu/tests/data/abc.data") at /work/GIT/apcu/apc_cache.c:403
#5  apc_load_data (data_file=0x7fffffffa740 "/work/GIT/apcu/tests/data/abc.data", cache=0x555555ce0740) at /work/GIT/apcu/apc_cache.c:433
#6  apc_cache_preload (cache=0x555555ce0740, path=0x555555bbd050 "/work/GIT/apcu/tests/data") at /work/GIT/apcu/apc_cache.c:466
#7  0x00007fffece83d8f in zm_startup_apcu (type=<optimized out>, module_number=16) at /work/GIT/apcu/php_apc.c:325
#8  0x0000555555795f1e in zend_startup_module_ex (module=0x555555c06980) at /usr/src/debug/php-5.6.20/Zend/zend_API.c:1758
#9  0x00005555557a25ab in zend_hash_apply (ht=ht@entry=0x555555b9a260 <module_registry>, 
    apply_func=apply_func@entry=0x555555795e10 <zend_startup_module_ex>) at /usr/src/debug/php-5.6.20/Zend/zend_hash.c:641
#10 0x0000555555799ffa in zend_startup_modules () at /usr/src/debug/php-5.6.20/Zend/zend_API.c:1885
#11 0x000055555572fb1b in php_module_startup (sf=<optimized out>, additional_modules=0x0, num_additional_modules=<optimized out>)
    at /usr/src/debug/php-5.6.20/main/main.c:2323
#12 0x00005555558431bd in php_cli_startup (sapi_module=<optimized out>) at /usr/src/debug/php-5.6.20/sapi/cli/php_cli.c:417
#13 0x000055555560f5b1 in main (argc=11, argv=0x555555bb0120) at /usr/src/debug/php-5.6.20/sapi/cli/php_cli.c:1358

```

**Comment by remicollet** [comment]
@krakjoe can you please review this ?

**Comment by krakjoe** [comment]
Is this in 5 branch still ?

**Comment by remicollet** [comment]
The bad data is in both 5 and 7 branch, but the segfault, fixed by above commit,  is only in 5 one.

**Comment by krakjoe** [comment]
I'm not able to reproduce this:

```
donekrakjoe@fiji:/usr/src/apcu$ TEST_PHP_EXECUTABLE=/opt/php/5.6/no-zts/debug/bin/php php5-nts -n -dextension=apcu.so tests/apc54_014.php
PHP 5.6.14-dev Development Server started at Wed Apr 20 09:38:16 2016
Listening on http://127.0.0.1:8008
Document root is /usr/src/apcu/tests
Press Ctrl-C to quit.
PHP 5.6.14-dev Development Server started at Wed Apr 20 09:38:16 2016
Listening on http://127.0.0.1:8009
Document root is /usr/src/apcu/tests
Press Ctrl-C to quit.
PHP 5.6.14-dev Development Server started at Wed Apr 20 09:38:16 2016
Listening on http://127.0.0.1:8010
Document root is /usr/src/apcu/tests
Press Ctrl-C to quit.
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
bool(true)
string(3) "123"
done
```

Also, there isn't anything wrong with the data: https://3v4l.org/qRSrE

ALLOC_INIT_ZVAL is right anyway.

**Comment by remicollet** [comment]
You also need to add

      -d apc.enabled=1 -d apc.enable_cli=1 -d apc.preload_path=$PWD/tests/data 

> Also, there isn't anything wrong with the data
```

$ php /tmp/foo.php 
string(6) "5.6.20"
string(3) "123"
$  php /tmp/foo.php 
string(9) "5.6.21RC1"
PHP Notice:  unserialize(): Error at offset 9 of 9 bytes in /tmp/foo.php on line 3
bool(false)

```

See https://bugs.php.net/71840

**Comment by remicollet** [comment]
The reproducer I use is 

    $ php -n -d extension=modules/apcu.so \
        -d apc.enabled=1 -d apc.enable_cli=1 -d apc.preload_path=$PWD/tests/data \
        -r 'var_dump(apcu_fetch("abc"));'

**Comment by remicollet** [comment]
Closing as 4.0.11 is released
