### ISSUE TITLE
Segfault in my_unserialize_object() with PHP7

### ISSUE THREAD

**Issue by Berdir** [krakjoe/apcu#177]
I need to see if I can isolate it, but I have a reproducible segfault in apcu with my behat application tests.

#0  my_unserialize_object (src=0x7fad528a1238, ctxt=0x7ffde8ceeef0, dst=0x7ffde8ceefd0) at /tmp/pear/temp/apcu/apc_cache.c:1218
#1  my_copy_zval (dst=dst@entry=0x7ffde8ceefd0, src=0x7fad528a1238, ctxt=0x7ffde8ceeef0) at /tmp/pear/temp/apcu/apc_cache.c:1521
#2  0x00007fad61350639 in apc_copy_zval (dst=0x7ffde8ceefd0, src=<optimized out>, ctxt=<optimized out>) at /tmp/pear/temp/apcu/apc_cache.c:1542
#3  0x00007fad613511c7 in apc_cache_fetch_internal (key=0x7fad4d54e1e0, t=1461367099, dst=0x7ffde8ceefb8, entry=0x7fad528a1238, cache=0x55f5e872fd20)
    at /tmp/pear/temp/apcu/apc_cache.c:503
#4  apc_cache_fetch (cache=0x55f5e872fd20, key=0x7fad4d54e1e0, t=t@entry=1461367099, dst=dst@entry=0x7ffde8ceefb8) at /tmp/pear/temp/apcu/apc_cache.c:973
#5  0x00007fad6134eb21 in zif_apcu_fetch (execute_data=<optimized out>, return_value=0x7fad61e149e0) at /tmp/pear/temp/apcu/php_apc.c:696
#6  0x00007fad66e5d32a in dtrace_execute_internal () from /usr/lib/apache2/modules/libphp7.0.so
#7  0x00007fad66ef0da0 in ?? () from /usr/lib/apache2/modules/libphp7.0.so
#8  0x00007fad66eacbeb in execute_ex () from /usr/lib/apache2/modules/libphp7.0.so
#9  0x00007fad66e5d1c1 in dtrace_execute_ex () from /usr/lib/apache2/modules/libphp7.0.so
#10 0x00007fad66ef0edd in ?? () from /usr/lib/apache2/modules/libphp7.0.so
#11 0x00007fad66eacbeb in execute_ex () from /usr/lib/apache2/modules/libphp7.0.so
#12 0x00007fad66e5d1c1 in dtrace_execute_ex () from /usr/lib/apache2/modules/libphp7.0.so

The line numbers might not be up to date anymore, I'll try to run it with the most recent version.

**Comment by Berdir** [comment]
Might no longer be able to reproduce with the latest version. I'll continue to test.

**Comment by Berdir** [comment]
Looks like this was indeed fixed, can't reproduce anymore.
